### PR TITLE
Hello-Microvers

### PR DESCRIPTION
**Pull request by sadat-Ramin**
Follow GitHub flow.
Open pull requests in GitHub.
Write descriptive, easy to understand commit messages.
Write short, detailed, easy to understand descriptions of pull requests.
Write a descriptive and easy to understand README in business English for every project submitted.
Demonstrate an ability to submit a project for code review.

### CODE REVIEW

**Review by NahnahAJ — CHANGES_REQUESTED** [review]
## Project Status: CHANGES REQUIRED :recycle: 
Hi @sadat-Ramin , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights :fire: 
- Professional README :heavy_check_mark: 
- Good use of GitHub Flow :heavy_check_mark: 
- Professional Pull Request Title and Summary :heavy_check_mark: 

## Required Changes ♻️
- You have done an amazing job so far @sadat-Ramin. :clap:  There are just a few changes you need to make and you'll be on your way to the next milestone :wink: 
- [x] From the project requirements, you were asked to add `node modules` to the `.gitignore` file. However, I noticed that you didn't add it. As a result, all the `node_modules` have been pushed to GitHub which has made you have about 5000+ files but this makes your project way too big and slow :worried: 
- Kindly ensure that `node modules` are ignored by Git and not pushed to Github. You should have just about 3 or 4 files changes instead of what you currently have :+1: 
- Your files
image

- [ ] Aside from the `node_modules`, per the project requirements, you need to create a `test.md` file and ensure that it is also ignored by Git and not pushed to GitHub as a result, it should also be included in the `.gitignore` file. So kindly implement this as well :wink: 
- [ ] Lastly, I noticed that you have the linter files in your project but I think they are not properly set up. So please ensure that the [HTML and CSS Linters ](https://github.com/microverseinc/linters-config) are well setup in your project and are passing :+1: 
- Your current linter checks
image
- What you should have
image

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- Consider starting your commit messages with a capital letter to make them more professional. eg. Creation of react app and addition of linter files is this a good commit message :wink:

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by wayungi — CHANGES_REQUESTED** [review]
Hi @sadat-Ramin , 

image

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


 ## Highlights
- [ ]  Correct GitHub flow ✔️ 
- [ ] Descriptive PR body 

 ## Required Changes ♻️
_Check the comments under the review._
- [ ] You have not set up your [GitHub workflows](https://github.com/microverseinc/linters-config/tree/master/html-css) so linters tests are not running on the remote repo. Please set the up so that linters can run. 



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by skyv26** [comment]
@sadat-Ramin Well done 👏🏻

**Comment by sadat-Ramin** [comment]
> @sadat-Ramin Well done 👏🏻

Hello
I solved the last problem of my project, but my last  request review is finished, can I merge my project?

**Review by Owusu-Desmond — APPROVED** [review]
Hi @sadat-Ramin , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
